/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rahul.joshi' at '2/8/16 3:22 PM' with Gradle 2.4
 *
 * @author rahul.joshi, @date 2/8/16 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
